name: $name
version: $version
main: com.moulberry.axiom.AxiomPaper
description: $description
authors:
  - Moulberry
api-version: "$apiVersion"
permissions:
  axiom.*:
    description: Allows use of all Axiom features
    default: op
folia-supported: true